name: CI-splain

on: [push]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), 'INCOMPLETE')"

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        scalaVersion: ["2.13.8"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build & test
        run: |
          ./dev/CI-latest-splain.sh -PscalaVersion=${{matrix.scalaVersion}}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            **/test-results/**/*.xml
